using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Grasshopper.Kernel;
using RhinoCodePluginGH.Components;

namespace ScriptParasite.Watcher;

public class ProjectHelper
{
    public static void EnsureVsCodeSettings(string workspaceRoot, bool force = false)
    {
        var settingsPath = Path.Combine(workspaceRoot, ".vscode", "settings.json");
        if (!force && File.Exists(settingsPath))
            return;

        var rhinoCodePath = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
            ".rhinocode", "py39-rh8");

        var pythonExe = Environment.OSVersion.Platform == PlatformID.Unix
            ? Path.Combine(rhinoCodePath, "bin", "python3")
            : Path.Combine(rhinoCodePath, "python.exe");

        var siteEnvsPath = Path.Combine(rhinoCodePath, "site-envs");
        var defaultEnv = Directory.Exists(siteEnvsPath)
            ? Directory.GetDirectories(siteEnvsPath, "default-*").FirstOrDefault()
            : null;

        var extraPaths = new List<string>
        {
            Path.Combine(rhinoCodePath, "site-stubs"),
            Path.Combine(rhinoCodePath, "site-rhinopython"),
            Path.Combine(rhinoCodePath, "site-rhinoghpython"),
            Path.Combine(rhinoCodePath, "site-interop"),
        };

        if (defaultEnv != null)
            extraPaths.Add(defaultEnv);

        var extraPathsJson = string.Join(",\n    ", extraPaths.Select(p => $"\"{Escape(p)}\""));

        var settings = $$"""
                         {
                           "python.analysis.extraPaths": [
                             {{extraPathsJson}}
                           ],
                           "python.defaultInterpreterPath": "{{Escape(pythonExe)}}"
                         }
                         """;

        Directory.CreateDirectory(Path.Combine(workspaceRoot, ".vscode"));
        File.WriteAllText(settingsPath, settings);
    }

    private static string Escape(string path) => path.Replace("\\", "\\\\");

    /// <summary>
    /// Writes a GrasshopperScripts.csproj next to the script so an IDE can resolve RhinoCommon,
    /// Grasshopper and the script-component base types (RhinoCodePluginGH). Reference paths are
    /// taken from the assemblies loaded in the running Rhino, so they follow the install location.
    /// Skipped when an existing IDE setup is found, unless <paramref name="force"/> is set
    /// (the "Regenerate IDE project" context menu item).
    /// </summary>
    public static bool EnsureProjectCsharp(string scriptFilename, bool force = false)
    {
        var directory = Path.GetDirectoryName(scriptFilename);
        if (directory == null) return false;

        if (!force && HasExistingProject(directory)) return true;

        var project = ProjectTemplate
            .Replace("%ghio%", typeof(GH_IO.Serialization.GH_IWriter).Assembly.Location)
            .Replace("%grasshopper%", typeof(GH_Component).Assembly.Location)
            .Replace("%rhinocommon%", typeof(Rhino.RhinoDoc).Assembly.Location)
            .Replace("%rhinocodeplugingh%", typeof(BaseLanguageComponent).Assembly.Location);

        try
        {
            File.WriteAllText(Path.Combine(directory, "GrasshopperScripts.csproj"), project);
            return true;
        }
        catch (Exception)
        {
            return false;
        }
    }

    /// <summary>
    /// Don't fight an existing IDE setup. A .csproj in this folder or any parent wins, because a
    /// parent SDK-style project globs subfolders and a nested csproj would double-compile the
    /// scripts. A .sln only counts in this folder; a parent solution doesn't claim the files.
    /// </summary>
    private static bool HasExistingProject(string directory)
    {
        if (Directory.EnumerateFiles(directory, "*.sln").Any()) return true;
        for (var dir = directory; dir != null; dir = Path.GetDirectoryName(dir))
        {
            if (Directory.EnumerateFiles(dir, "*.csproj").Any()) return true;
        }
        return false;
    }

    private const string ProjectTemplate = @"<!-- Auto-generated by ScriptParasite. Delete to regenerate; edit to customize (plugin will leave edits alone). -->
<Project Sdk=""Microsoft.NET.Sdk"">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <NoWarn>CS7011;CS0105;CS0649</NoWarn>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <!-- Scripts are compiled by Rhino at runtime; this project only exists for IDE IntelliSense. -->
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include=""GH_IO"">
      <HintPath>%ghio%</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include=""Grasshopper"">
      <HintPath>%grasshopper%</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include=""RhinoCommon"">
      <HintPath>%rhinocommon%</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include=""RhinoCodePluginGH"">
      <HintPath>%rhinocodeplugingh%</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>";
}
